clang/riscv: optimize multilib select for nuclei riscv
clang/riscv: workaround to let arch contains v ext find library without v ext

$ /Local/hqfang/workspace/software/riscv-gnu-toolchain/LocalInstall/linux64/newlibc/2023.07/gcc/bin/riscv64-unknown-elf-clang -march=rv32imafdc -mabi=ilp32d -print-search-dirs -v
clang version 17.0.0 (git@gito:software/devtools/llvm-project c7ad6d52a78fdc05a465c02d5fe117445c72f451)
Target: riscv32-unknown-unknown-elf
Thread model: posix
InstalledDir: /Local/hqfang/workspace/software/riscv-gnu-toolchain/LocalInstall/linux64/newlibc/2023.07/gcc/bin
Found candidate GCC installation: /Local/hqfang/workspace/software/riscv-gnu-toolchain/LocalInstall/linux64/newlibc/2023.07/gcc/bin/../lib/gcc/riscv64-unknown-elf/13.1.1
Selected GCC installation: /Local/hqfang/workspace/software/riscv-gnu-toolchain/LocalInstall/linux64/newlibc/2023.07/gcc/bin/../lib/gcc/riscv64-unknown-elf/13.1.1
Candidate multilib: rv32ic/ilp32;@march=rv32ic@mabi=ilp32
Candidate multilib: rv32iac/ilp32;@march=rv32iac@mabi=ilp32
Candidate multilib: rv32imc/ilp32;@march=rv32imc@mabi=ilp32
Candidate multilib: rv32imac/ilp32;@march=rv32imac@mabi=ilp32
Candidate multilib: rv32imafc/ilp32f;@march=rv32imafc@mabi=ilp32f
Candidate multilib: rv32imafdc/ilp32d;@march=rv32imafdc@mabi=ilp32d
Candidate multilib: rv32imafdc/ilp32d;@march=rv32imafdcv@mabi=ilp32d
Candidate multilib: rv64imac/lp64;@march=rv64imac@mabi=lp64
Candidate multilib: rv64imafc/lp64f;@march=rv64imafc@mabi=lp64f
Candidate multilib: rv64imafdc/lp64d;@march=rv64imafdc@mabi=lp64d
Candidate multilib: rv64imafdc/lp64d;@march=rv64imafdcv@mabi=lp64d
Candidate multilib: rv32imac_zba_zbb_zbc_zbs/ilp32;@march=rv32imac_zba_zbb_zbc_zbs@mabi=ilp32
Candidate multilib: rv32imafc_zba_zbb_zbc_zbs/ilp32f;@march=rv32imafc_zba_zbb_zbc_zbs@mabi=ilp32f
Candidate multilib: rv32imafdc_zba_zbb_zbc_zbs/ilp32d;@march=rv32imafdc_zba_zbb_zbc_zbs@mabi=ilp32d
Candidate multilib: rv64imac_zba_zbb_zbc_zbs/lp64;@march=rv64imac_zba_zbb_zbc_zbs@mabi=lp64
Candidate multilib: rv64imafc_zba_zbb_zbc_zbs/lp64f;@march=rv64imafc_zba_zbb_zbc_zbs@mabi=lp64f
Candidate multilib: rv64imafdc_zba_zbb_zbc_zbs/lp64d;@march=rv64imafdc_zba_zbb_zbc_zbs@mabi=lp64d
Candidate multilib: rv64imafdc_zba_zbb_zbc_zbs/lp64d;@march=rv64imafdcv_zba_zbb_zbc_zbs@mabi=lp64d
Selected multilib: rv32imafdc/ilp32d;@march=rv32imafdc@mabi=ilp32d
Found CUDA installation: /usr/lib/cuda, version
programs: =/Local/hqfang/workspace/software/riscv-gnu-toolchain/LocalInstall/linux64/newlibc/2023.07/gcc/bin:/Local/hqfang/workspace/software/riscv-gnu-toolchain/LocalInstall/linux64/newlibc/2023.07/gcc/bin/../lib/gcc/riscv64-unknown-elf/13.1.1/../../../../riscv64-unknown-elf/bin:/Local/hqfang/workspace/software/riscv-gnu-toolchain/LocalInstall/linux64/newlibc/2023.07/gcc/bin/../lib/gcc/riscv64-unknown-elf/13.1.1/../../../../bin
libraries: =/Local/hqfang/workspace/software/riscv-gnu-toolchain/LocalInstall/linux64/newlibc/2023.07/gcc/lib/clang/17:/Local/hqfang/workspace/software/riscv-gnu-toolchain/LocalInstall/linux64/newlibc/2023.07/gcc/bin/../lib/gcc/riscv64-unknown-elf/13.1.1/rv32imafdc/ilp32d:/Local/hqfang/workspace/software/riscv-gnu-toolchain/LocalInstall/linux64/newlibc/2023.07/gcc/bin/../lib/gcc/riscv64-unknown-elf/13.1.1/../../../../riscv64-unknown-elf/lib/rv32imafdc/ilp32d:/Local/hqfang/workspace/software/riscv-gnu-toolchain/LocalInstall/linux64/newlibc/2023.07/gcc/bin/../lib/gcc/riscv64-unknown-elf/13.1.1:/Local/hqfang/workspace/software/riscv-gnu-toolchain/LocalInstall/linux64/newlibc/2023.07/gcc/bin/../lib/gcc/riscv64-unknown-elf/13.1.1/../../../../riscv64-unknown-elf/lib

Signed-off-by: Huaqi Fang <578567190@qq.com>

clang/riscv: add missing rv32 with vector multilib

Signed-off-by: Huaqi Fang <578567190@qq.com>

clang/riscv: fix and optimize multilib search rule

Signed-off-by: Huaqi Fang <578567190@qq.com>

clang/riscv: fix llvm::join function not found

/work/llvm/clang/lib/Driver/ToolChains/Gnu.cpp:1809:24: error: ‘join’ is not a member of ‘llvm’

Signed-off-by: Huaqi Fang <578567190@qq.com>